version: '3'

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    environment:
      - APIROAD_KEY=${APIROAD_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules