version: '3'

services:
  scraper:
    build: .
    environment:
      - APIROAD_KEY=${APIROAD_KEY}
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - db

  db:
    image: busybox
    volumes:
      - ./data:/usr/src/app/data
